version: '3'
services:
  learning-nginx:
    image: nginx:latest
    container_name: learning-nginx
    networks:
      - learning-network
    depends_on:
      - learning-php-fpm
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./dev/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  learning-php-fpm:
    build:
      context: ./dev/php-fpm
    container_name: learning-php-fpm
    networks:
      - learning-network
    links:
      - learning-mysql
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
      - ./dev/php-fpm/php.ini:/usr/local/etc/php/php.ini

  learning-mysql:
    image: mysql:5.7
    container_name: learning-mysql
    networks:
      - learning-network
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=demo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./dev/mysql/data:/var/lib/mysql
  learning-sphinxsearch:
    image: macbre/sphinxsearch:latest
    container_name: learning-sphinxsearch
    networks:
      - learning-network
    depends_on:
      - learning-mysql
    ports:
      - "9306:9306"
      - "9312:9312"
    volumes:
      - ./dev/sphinx/conf/sphinx.conf:/opt/sphinx/conf/sphinx.conf
      - ./dev/sphinx/conf/indexes/:/opt/sphinx/conf/indexes/
      - ./dev/sphinx/logs/:/var/log/sphinx/
      - ./dev/sphinx/indexes/:/opt/sphinx/index/

networks:
  learning-network:
    driver: bridge
